### ISSUE TITLE
Add trailing slash to host slug in the http-api.md

### ISSUE THREAD

**Issue by blaisep** [ArweaveTeam/docs.arweave.org-developers#15]
An issue was opened in [ArweaveTeam/docs.arweave.org-info](https://github.com/ArweaveTeam/docs.arweave.org-info/issues/8) by mistake, it belongs in this repo because there is a missing slash in:
https://github.com/ArweaveTeam/docs.arweave.org-developers/blame/master/server/http-api.md#L810

**Comment by blaisep** [comment]
Fixed in https://github.com/ArweaveTeam/docs.arweave.org-developers/pull/16

**Comment by oritwoen** [comment]
PR was approved: https://github.com/ArweaveTeam/docs.arweave.org-developers/pull/17

Issue to be closed @blaisep  :)
