### ISSUE TITLE
if no tokens are being transferred use an empty string

### ISSUE THREAD

**Issue by rosmcmahon** [ArweaveTeam/docs.arweave.org-developers#23]
![image](https://user-images.githubusercontent.com/1430130/149688019-bbe9cd2d-9883-4a6c-b665-9812ac7fc521.png)

**Comment by rosmcmahon** [comment]
thanks to Gialosai#9915 for noticing this

**Comment by fuadop** [comment]
🤔 what should be there ? @rosmcmahon 

`Use "0", if no tokens are being transferred` ?

**Comment by rosmcmahon** [comment]
that requirement is gone now. no need to add optional `quantity` (or `data` for that matter) @fuadop

**Comment by fuadop** [comment]
Okay @rosmcmahon 🚀.

**Comment by rosmcmahon** [comment]
text updated. closing
