### ISSUE TITLE
Sample request doesn't work - Out of date maybe?

### ISSUE THREAD

**Issue by LeGaryGary** [ArweaveTeam/docs.arweave.org-developers#4]
In the file: `server/http-api.md`

It has a [sample request in multiple formats](https://docs.arweave.org/developers/server/http-api#sample-request)

When executing the curl command I get the following:
`curl: (7) Failed to connect to arweave.net port 1984: Connection refused`

I believe this is because the URL / port might have changed

**Comment by arweave-kyle** [comment]
Hey @LeGaryGary, fixed!

**Comment by LeGaryGary** [comment]
Thanks Kyle :)
